### ISSUE TITLE
Context binding feature

### ISSUE THREAD

**Issue by lpinca** [Morglod/tseep#20]
It seems that inside a listener, the value of `this` is not set to the `EventEmitter` instance.

```js
import assert from 'node:assert';
import { EventEmitter } from 'tseep';

const ee = new EventEmitter();

ee.on('foo', function () {
  assert.strictEqual(this, ee);
});

ee.emit('foo');
```

This is a fundamental feature of the Node.js `EventEmitter`, see https://nodejs.org/api/events.html#passing-arguments-and-this-to-listeners.

**Comment by Morglod** [comment]
I agree that I should write something like (not drop-in replacement for node's eventemitter).

But there is nothing "fundamental" in it.
Its some strange anti-pattern as most of other "fundamental" things in node's emitter, which no one should rely on.

**Comment by lpinca** [comment]
> Its some strange anti-pattern as most of other "fundamental" things in node's emitter, which no one should rely on.

That is your personal opinion which I respect but I disagree. It is feature present since the early days of the `EventEmitter` and is _heavily_ relied on in Node.js core and many user-land modules. It allows to avoid calling `Function.prototype.bind()` every time.

**Comment by Morglod** [comment]
There are also 'newListener'/'removeListener'/'error' events which also presents since the same early days. Which I think is more useful than this fundamental thing, but ee3 has no implementations for this.

Without this fundamental thing, you could just:

```
ee.on('foo', function () {
  const self = ee;
  // do whatever you like
  assert.strictEqual(self, ee);
});
```

Could you give please some examples of packages which rely on this thing?

**Comment by lpinca** [comment]
Some examples on top of my mind are:

- https://github.com/pinojs/thread-stream.
- https://github.com/websockets/ws (I am a maintainer).

> Without this fundamental thing, you could just:

Which means using a wrapper function for every listener just like `Function.prototype.bind()`.

**Comment by Morglod** [comment]
I see, thanks for links!
So real example is inheritance thing where you have no reference to instance other than `this.`

I dislike inheritance thing, but agree that its common pattern everywhere
Will try to implement it (or make some kind of "compatibility" version)

Do you have any other missing features needed?

**Comment by lpinca** [comment]
No, thank you. I actually don't need the feature as I'm not planning to use an external dependency for the `EventEmitter`. Maybe for the browser but I'm not writing any front-end code at the moment.

**Comment by mustafa519** [comment]
Fixing this issue will break the `__proto__ = null` optimization?

Well, I mostly have to bind the instance otherwise it causes `Cannot read properties of undefined (reading 'events')` error. Especially, if I need to pass the `events` variable, which was defined as `EventEmitter` instance.

So, if it kills the optimization, what would you suggest instead? Or would you consider adding an option like `autoBind: true`?

**Comment by Morglod** [comment]
Found only one solution without impact on performance. 
The problem is that any change around context binding inside hot path (.emit) results in bad JIT code & allocations.

Added `addListenerBound` / `removeListenerBound` that binds listener to EventEmitter or other specified context.

https://github.com/Morglod/tseep/commit/552b31066508b4cc38ffe9b45c1871a527e02b23
