### ISSUE TITLE
Is there a way to "inject" context into listener callbacks?

### ISSUE THREAD

**Issue by xorweak** [Morglod/tseep#24]
For example, something like this

```
const context = { hello: 'world' }
const data = { bye: 'world' }

this.emit('request', data).apply(context)



MyCustomClass.on('request', function (data) {
 console.log('whoiam?', this) // prints { hello: 'world' }
});
```

**Comment by Morglod** [comment]
Hi!

For this purposes I added `addListenerBound`

Its different method, because tracking context eats some performance and mostly in modern development its not needed (because you always have context rather than with inheritance in old code).

So for your case:
```ts
MyCustomClass.addListenerBound('request', function (data) {
 console.log('whoiam?', this) // prints { hello: 'world' }
});
```

or with custom context

```ts
MyCustomClass.addListenerBound('request', function (data) {
}, CUSTOM_CONTEXT);
```

--

not sure what you want to achieve with calling 'apply' on boolean from 'emit'
